spring.application.name=TourEksamen
spring.datasource.url=jdbc:mysql://localhost:3306/tourEksamenNy
spring.jpa.hibernate.ddl-auto=create-drop
spring.datasource.username=123
spring.datasource.password=123
server.error.include-stacktrace=always